name: Build core-image-mininal image

on: [push, workflow_dispatch]

env:
  DL_PATH: /home/marc/mnt/projet/yocto-downloads
  SSTATE_PATH: /home/marc/mnt/projet/yocto-sstate-cache

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run kas checkout
        run: env DL_DIR="$DL_PATH" SSTATE_DIR="$SSTATE_PATH" kas checkout kas-ghdemo.yml
      - name: Run kas build
        run: env DL_DIR="$DL_PATH" SSTATE_DIR="$SSTATE_PATH" kas build kas-ghdemo.yml
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: core-image-minimal.tar.gz-${{ github.sha }}
          path: ./build/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.tar.gz
